---
# tasks file for hswong3i.mysql_vhosts

- name: create mysql user
  become: true
  become_user: root
  mysql_user:
    name: "{{ mysql_vhosts_user }}"
    password: "{{ mysql_vhosts_pass }}"
  when: mysql_vhosts_pass is string
  tags: hswong3i.mysql_vhosts

- name: create mysql db
  become: true
  become_user: root
  mysql_db:
    name: "{{ mysql_vhosts_id }}"
    encoding: "{{ mysql_vhosts_encoding }}"
    collation: "{{ mysql_vhosts_collation }}"
  tags: hswong3i.mysql_vhosts

- name: append privs for mysql user
  become: true
  become_user: root
  mysql_user:
    name: "{{ mysql_vhosts_user }}"
    host: "{{ item.host }}"
    priv: "{{ item.priv }}"
    append_privs: "yes"
  with_items: "{{ mysql_vhosts_privs }}"
  tags: hswong3i.mysql_vhosts
