---
# tasks file for hswong3i.mysql_db

- name: create mysql db
  mysql_db:
    name="{{ mysql_db_name }}"
    encoding="{{ mysql_db_encoding }}"
    collation="{{ mysql_db_collation }}"
  tags: hswong3i.mysql_db
